version: '3.8'
services:
  wordpress:
    image: wordpress:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./wp-data:/var/www/html
      - ./apache-custom.conf:/etc/apache2/conf-available/custom.conf
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini  # Mount custom php.ini
    ports:
      - "8061:80"  # Expose port 8061 directly
